### ISSUE TITLE
MacOS 下 Logging Path

### ISSUE THREAD

**Issue by jangrui** [alvis-u/uexam#7]
默认路径 `/usr/log/path` 无权限

更改目录即可
```
logging:
  config: classpath:logback-spring.xml
  file: exam
  path: ./log/exam/
```
